FROM ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive

# pre-install softwares
COPY ./sources.list.2404 /etc/apt/sources.list
RUN dpkg --add-architecture i386
RUN apt-get -y update && apt-get upgrade -y
RUN apt-get install -y lib32z1 apt-transport-https \
    python3 python3-pip python3-venv python3-poetry python3-dev python3-setuptools \
    libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev libc6-dbg libc6-dbg:i386 libgcc-s1:i386 \
    vim nano netcat-openbsd openssh-server git unzip curl tmux konsole wget sudo \
    bison flex build-essential gcc-multilib \
    qemu-system-x86 qemu-user qemu-user-binfmt \
    gcc gdb gdbserver gdb-multiarch clang lldb make cmake
RUN apt install -y patchelf zsh

# enable ssh login
RUN rm -f /etc/service/sshd/down
RUN sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config &&\
    sed -ri 's/#UseDNS\ no/UseDNS\ no/g' /etc/ssh/sshd_config && \
    sed -ri "s/StrictModes yes/StrictModes no/g" /etc/ssh/sshd_config && \
    sed -ri "s/UsePAM yes/UsePAM no/g" /etc/ssh/sshd_config

# enable login with password
RUN echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config
RUN echo "root:root" | chpasswd

# add sudo
RUN usermod -aG sudo ubuntu

# enable ssh key login
#RUN mkdir /home/ubuntu/.ssh && \
#    echo "Your ssh key" > /home/ubuntu/.ssh/authorized_keys

# keep container running
RUN echo "#!/bin/sh\nservice ssh restart\nsleep infinity" > /root/start.sh
RUN chmod +x /root/start.sh

# create venv for pip
RUN python3 -m venv /pip_venv
#&& \
#    chown -R ubuntu:ubuntu /pip_venv && \
#    echo "\n\n# pip venv\nsource /pip_venv/bin/activate" >> /home/ubuntu/.bashrc

# pwn-related tools
RUN mkdir /root/.pip/
COPY ./pip.conf /root/.pip/
RUN /pip_venv/bin/pip install -U pip && \
    /pip_venv/bin/pip install --no-cache-dir \
    pwntools \
    ropgadget \
    z3-solver \
    smmap2 \
    apscheduler \
    ropper \
    unicorn \
    keystone-engine \
    capstone \
    angr \
    pebble \
    r2pipe \
    LibcSearcher \
    poetry

# pwndbg
COPY ./pwndbg /root/pwndbg
RUN cd /root/pwndbg && chmod +x setup.sh && bash -x setup.sh

# tmux & ZSH
COPY ./tmux.conf /root/.tmux.conf
COPY ./ohmyzsh_install.sh /tmp/ohmyzsh_install.sh
RUN chmod +x /tmp/ohmyzsh_install.sh && sh -c /tmp/ohmyzsh_install.sh
RUN chsh -s /bin/zsh root
COPY ./zsh-autosuggestions /root/.oh-my-zsh/custom/plugins/zsh-autosuggestions
COPY ./zsh-syntax-highlighting /root/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
COPY ./zshrc /root/.zshrc

# one gadget
RUN apt install -y ruby-full && gem install one_gadget

# locale
RUN apt-get install locales && locale-gen en_US.UTF-8 && update-locale

# xclibc
COPY ./xclibc /usr/local/bin/xclibc
RUN chmod +x /usr/local/bin/xclibc && apt install -y bc

# nvim
RUN apt install -y nodejs npm && npm config set registry http://10.100.3.3:8081/repository/npm/ && \
	npm install -g n
RUN n lts	
COPY ./nvim /root/nvim
RUN mkdir -p /root/.local/share/nvim/site/autoload/ && mkdir -p /root/.config/nvim
RUN cp /root/nvim/plug.vim /root/.local/share/nvim/site/autoload/
RUN cp /root/nvim/init.vim /root/.config/nvim
RUN cp /root/nvim/coc-settings.json /root/.config/nvim
RUN cp -r /root/nvim/plugged /root/.local/share/nvim/
RUN mkdir /root/.config/coc
RUN cp -r /root/nvim/extensions /root/.config/coc




CMD ["/root/start.sh"]
