version: '3.0'

services:
  webapp:
    image: pwn_ubuntu_2424:latest
    container_name: pwn_ubuntu_2424
    ports:
      - "2222:22" 
    volumes:
      - ./glibc-all-in-one:/root/glibc-all-in-one
      - ../tasks/:/home/task 
      - ../../how2heap:/home/how2heap/
    restart: unless-stopped
