export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

plugins=(
  git zsh-autosuggestions vi-mode colored-man-pages
  history-substring-search vscode
  zsh-syntax-highlighting command-not-found
)

source $ZSH/oh-my-zsh.sh
source /pip_venv/bin/activate
export PATH="$PATH:/root/nvim/bin"
