# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  # https://docs.readthedocs.com/platform/stable/build-customization.html#install-dependencies-with-uv
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - uv venv
    install:
      - uv sync --only-group docs
    build:
      html:
        - uv run --only-group docs sphinx-build -T -b html docs $READTHEDOCS_OUTPUT/html

mkdocs:
  configuration: mkdocs.yml
